# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: risk_engine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'risk_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11risk_engine.proto\x12\nriskengine\"B\n\x0bRiskRequest\x12\x14\n\x0c\x63ircuit_data\x18\x01 \x01(\t\x12\x0e\n\x06qubits\x18\x02 \x01(\x05\x12\r\n\x05\x64\x65pth\x18\x03 \x01(\x05\"9\n\x0cRiskResponse\x12\x12\n\nrisk_score\x18\x01 \x01(\x02\x12\x15\n\rprovider_used\x18\x02 \x01(\t2R\n\x0cRiskAnalysis\x12\x42\n\x0b\x41nalyzeRisk\x12\x17.riskengine.RiskRequest\x1a\x18.riskengine.RiskResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'risk_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RISKREQUEST']._serialized_start=33
  _globals['_RISKREQUEST']._serialized_end=99
  _globals['_RISKRESPONSE']._serialized_start=101
  _globals['_RISKRESPONSE']._serialized_end=158
  _globals['_RISKANALYSIS']._serialized_start=160
  _globals['_RISKANALYSIS']._serialized_end=242
# @@protoc_insertion_point(module_scope)
